import type { Dish, Lang, ThemeMode } from '@/types/recipe';

export interface VerifiedDishData {
  id: string;
  slug: string;
  zh: string;
  en: string;
  meal_type: 'breakfast' | 'lunch' | 'dinner';
  season: ThemeMode | 'all';
  cuisine: string;
  prep_time: string;
  calories: string;
  image_url: string;
  dietary_tags: string[];
  ingredientsZh: Array<{ name: string; amount: string }>;
  ingredientsEn: Array<{ name: string; amount: string }>;
  stepsZh: string[];
  stepsEn: string[];
  chefTipsZh: string;
  chefTipsEn: string;
}

export const VERIFIED_MASTER_POOL: VerifiedDishData[] = [
  // ================= 早餐 (10道独立菜品与独家图片) =================
  {
    id: 'b-avocado-egg',
    slug: 'avocado-poached-egg-toast',
    zh: '牛油果水波蛋全麥吐司',
    en: 'Avocado Poached Egg Sourdough',
    meal_type: 'breakfast',
    season: 'spring',
    cuisine: 'Western Healthy',
    prep_time: '12 mins',
    calories: '320 kcal',
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['vegetarian', 'high_protein', 'seasonal_produce'],
    ingredientsZh: [{ name: '酸種全麥吐司', amount: '2片 (80g)' }, { name: '新鮮牛油果', amount: '半個 (75g)' }, { name: '走地雞蛋', amount: '1顆' }, { name: '初榨橄欖油', amount: '1茶匙 (5ml)' }],
    ingredientsEn: [{ name: 'Sourdough Toast', amount: '2 slices (80g)' }, { name: 'Fresh Avocado', amount: '1/2 (75g)' }, { name: 'Free-range Egg', amount: '1 pc' }, { name: 'Olive Oil', amount: '1 tsp (5ml)' }],
    stepsZh: ['吐司烘烤至兩面金黃微焦。', '牛油果搗成泥加少許海鹽檸檬汁抹在吐司上。', '煮微沸水打入雞蛋慢煮3分鐘，撈出瀝乾置於吐司頂部。'],
    stepsEn: ['Toast sourdough slices until golden and crisp.', 'Mash avocado with sea salt and lemon juice, spread over toast.', 'Poach egg in simmering water for 3 mins, place atop toast.'],
    chefTipsZh: '煮水波蛋時在水裡加幾滴白醋，能讓蛋清迅速收攏光滑。',
    chefTipsEn: 'Add a dash of vinegar to simmering water to keep the egg white perfectly compact.',
  },
  {
    id: 'b-greek-yogurt',
    slug: 'seasonal-berry-greek-yogurt',
    zh: '時令莓果希臘優格碗',
    en: 'Seasonal Berry Greek Yogurt Bowl',
    meal_type: 'breakfast',
    season: 'summer',
    cuisine: 'Mediterranean',
    prep_time: '8 mins',
    calories: '240 kcal',
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['vegetarian', 'low_calorie', 'seasonal_produce', 'gluten_free'],
    ingredientsZh: [{ name: '無糖希臘優格', amount: '180g' }, { name: '新鮮藍莓與草莓', amount: '80g' }, { name: '烘烤堅果碎', amount: '15g' }, { name: '純天然蜂蜜', amount: '1茶匙 (10g)' }],
    ingredientsEn: [{ name: 'Greek Yogurt', amount: '180g' }, { name: 'Fresh Berries', amount: '80g' }, { name: 'Roasted Nuts', amount: '15g' }, { name: 'Honey', amount: '1 tsp (10g)' }],
    stepsZh: ['優格舀入碗中鋪平。', '洗淨的莓果切塊鋪在優格表面。', '撒上堅果碎並均勻淋上一圈蜂蜜。'],
    stepsEn: ['Spoon Greek yogurt into bowl.', 'Top with fresh rinsed berries and crushed nuts.', 'Drizzle evenly with pure honey.'],
    chefTipsZh: '選用無糖純希臘優格，蛋白質含量更高且口感如乳酪般絲滑。',
    chefTipsEn: 'Use authentic strained Greek yogurt for high protein and velvety texture.',
  },
  {
    id: 'b-scallop-congee',
    slug: 'silky-rice-scallop-congee',
    zh: '瑤柱滑雞絲白米粥佐溏心蛋',
    en: 'Silky Rice Congee with Scallop & Egg',
    meal_type: 'breakfast',
    season: 'all',
    cuisine: 'Cantonese',
    prep_time: '25 mins',
    calories: '230 kcal',
    image_url: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['gluten_free', 'low_sodium', 'toddler_friendly'],
    ingredientsZh: [{ name: '優質大米', amount: '50g' }, { name: '乾干貝 (瑤柱)', amount: '15g' }, { name: '溏心蛋', amount: '1顆' }, { name: '香蔥薑絲', amount: '適量' }],
    ingredientsEn: [{ name: 'Jasmine Rice', amount: '50g' }, { name: 'Dried Scallops', amount: '15g' }, { name: 'Soft Boiled Egg', amount: '1 pc' }, { name: 'Ginger & Scallion', amount: 'pinch' }],
    stepsZh: ['大米與泡發撕碎的干貝一同下鍋，加足量清水大火煮沸。', '轉小火慢煨20分鐘並順時針攪拌至米粥起膠。', '出鍋前撒薑絲海鹽，搭配半顆溏心蛋。'],
    stepsEn: ['Simmer rice and shredded scallops in water over medium heat.', 'Stir for 20 mins until rich and creamy.', 'Season with ginger and sea salt, garnish with egg.'],
    chefTipsZh: '淘米後滴兩滴油拌勻冷凍片刻再煮，15分鐘即可熬出濃稠米油。',
    chefTipsEn: 'Freezing washed grains with a drop of oil helps break starches faster.',
  },
  {
    id: 'b-steamed-dumpling',
    slug: 'emerald-vegetable-dumplings',
    zh: '翡翠薺菜鮮蝦蒸餃',
    en: 'Steamed Shrimp & Green Dumplings',
    meal_type: 'breakfast',
    season: 'spring',
    cuisine: 'Chinese',
    prep_time: '18 mins',
    calories: '280 kcal',
    image_url: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['high_protein', 'seasonal_produce'],
    ingredientsZh: [{ name: '鮮蝦薺菜餃', amount: '6只 (150g)' }, { name: '香醋薑絲汁', amount: '15ml' }],
    ingredientsEn: [{ name: 'Handmade Dumplings', amount: '6 pcs (150g)' }, { name: 'Ginger Black Vinegar', amount: '15ml' }],
    stepsZh: ['蒸鍋加水大火燒沸。', '蒸屜刷少許薄油，碼入蒸餃大火蒸8分鐘。', '取出搭配香醋汁溫熱食用。'],
    stepsEn: ['Bring water in steamer to rolling boil.', 'Arrange dumplings on oiled rack, steam on high for 8 mins.', 'Serve immediately with dipping vinegar.'],
    chefTipsZh: '蒸屜刷油能防止餃子皮破裂漏汁。',
    chefTipsEn: 'Lightly oil the steamer rack to prevent dumpling skins from tearing.',
  },
  {
    id: 'b-smoked-salmon-bagel',
    slug: 'smoked-salmon-dill-bagel',
    zh: '煙熏三文魚蒔蘿全麥貝果',
    en: 'Smoked Salmon Dill Wholewheat Bagel',
    meal_type: 'breakfast',
    season: 'spring',
    cuisine: 'Nordic',
    prep_time: '10 mins',
    calories: '360 kcal',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['high_protein', 'seasonal_produce'],
    ingredientsZh: [{ name: '全麥貝果', amount: '1個' }, { name: '挪威煙熏三文魚', amount: '70g' }, { name: '低脂奶油芝士', amount: '20g' }, { name: '新鮮蒔蘿與酸豆', amount: '少許' }],
    ingredientsEn: [{ name: 'Wholewheat Bagel', amount: '1 pc' }, { name: 'Smoked Salmon', amount: '70g' }, { name: 'Light Cream Cheese', amount: '20g' }, { name: 'Fresh Dill & Capers', amount: 'pinch' }],
    stepsZh: ['貝果對半切開烘烤至邊緣酥脆。', '抹上奶油芝士，鋪上煙熏三文魚片。', '點綴蒔蘿、酸豆與現磨黑胡椒。'],
    stepsEn: ['Slice and toast bagel until edges are crisp.', 'Spread cream cheese and layer smoked salmon.', 'Top with dill, capers, and freshly ground pepper.'],
    chefTipsZh: '擠上兩滴檸檬汁能有效提升煙熏三文魚的鮮美度。',
    chefTipsEn: 'A light squeeze of lemon balances the richness of the salmon.',
  },
  {
    id: 'b-truffle-scramble',
    slug: 'truffle-wild-mushroom-scramble',
    zh: '黑松露野菌嫩滑炒蛋吐司',
    en: 'Truffle Wild Mushroom Scramble Toast',
    meal_type: 'breakfast',
    season: 'winter',
    cuisine: 'French',
    prep_time: '12 mins',
    calories: '330 kcal',
    image_url: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['vegetarian', 'high_protein', 'keto_friendly'],
    ingredientsZh: [{ name: '有機雞蛋', amount: '3顆' }, { name: '黑松露醬', amount: '1茶匙 (8g)' }, { name: '口蘑與褐菇', amount: '60g' }, { name: '發酵黃油', amount: '10g' }],
    ingredientsEn: [{ name: 'Organic Eggs', amount: '3 pcs' }, { name: 'Truffle Paste', amount: '1 tsp (8g)' }, { name: 'Mushrooms', amount: '60g' }, { name: 'Butter', amount: '10g' }],
    stepsZh: ['黃油熱鍋，下蘑菇片翻炒至微黃焦香盛出。', '蛋液加少許鮮奶打散，低溫入鍋慢慢推炒成絹豆腐狀。', '關火拌入黑松露醬與炒蘑菇裝盤。'],
    stepsEn: ['Sauté mushrooms in butter until fragrant and golden.', 'Whisk eggs with a splash of milk, softly scramble over gentle heat.', 'Fold in truffle paste and mushrooms off the heat.'],
    chefTipsZh: '炒蛋全程保持微小火，利用鍋底餘溫凝固才能保證極致嫩滑。',
    chefTipsEn: 'Keep flame extremely low and let residual heat finish the scramble.',
  },
  {
    id: 'b-pumpkin-oatmeal',
    slug: 'golden-pumpkin-spiced-oatmeal',
    zh: '金黃南瓜肉桂燕麥暖粥',
    en: 'Golden Pumpkin Spiced Oatmeal',
    meal_type: 'breakfast',
    season: 'autumn',
    cuisine: 'Healthy',
    prep_time: '15 mins',
    calories: '280 kcal',
    image_url: 'https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['vegan', 'dairy_free', 'seasonal_produce'],
    ingredientsZh: [{ name: '傳統大燕麥片', amount: '50g' }, { name: '時令南瓜泥', amount: '100g' }, { name: '燕麥奶', amount: '200ml' }, { name: '肉桂粉與楓糖漿', amount: '適量' }],
    ingredientsEn: [{ name: 'Rolled Oats', amount: '50g' }, { name: 'Pumpkin Puree', amount: '100g' }, { name: 'Oat Milk', amount: '200ml' }, { name: 'Cinnamon & Maple', amount: 'to taste' }],
    stepsZh: ['燕麥片與燕麥奶入鍋小火慢煮5分鐘至軟糯。', '加入南瓜泥攪拌均勻，微沸煮2分鐘。', '盛入碗中撒少許肉桂粉與堅果。'],
    stepsEn: ['Cook oats in oat milk over low heat for 5 mins.', 'Stir in pumpkin puree and simmer for 2 mins.', 'Sprinkle with cinnamon powder and toasted seeds.'],
    chefTipsZh: '自製蒸南瓜泥自帶天然清甜，無需額外添加精製糖。',
    chefTipsEn: 'Naturally sweet pumpkin puree eliminates the need for added refined sugar.',
  },

  // ================= 午餐 (10道独立菜品与独家图片) =================
  {
    id: 'l-steamed-seabass',
    slug: 'cantonese-steamed-seabass',
    zh: '鮮甜蔥薑清蒸春鱸魚柳',
    en: 'Cantonese Steamed Spring Seabass Fillet',
    meal_type: 'lunch',
    season: 'spring',
    cuisine: 'Cantonese',
    prep_time: '18 mins',
    calories: '280 kcal',
    image_url: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['gluten_free', 'high_protein', 'dairy_free', 'seasonal_produce'],
    ingredientsZh: [{ name: '新鮮鱸魚柳', amount: '250g' }, { name: '老薑絲與大蔥絲', amount: '35g' }, { name: '優質蒸魚豉油', amount: '2湯匙 (30ml)' }, { name: '滾燙花生油', amount: '1湯匙 (15ml)' }],
    ingredientsEn: [{ name: 'Seabass Fillet', amount: '250g' }, { name: 'Ginger & Scallion Julienne', amount: '35g' }, { name: 'Steamed Fish Soy Sauce', amount: '2 tbsp (30ml)' }, { name: 'Hot Peanut Oil', amount: '1 tbsp (15ml)' }],
    stepsZh: ['鱸魚柳洗淨擦乾，盤底鋪蔥薑架空魚身。', '蒸鍋上汽後大火清蒸7分鐘。', '倒掉盤中腥水，鋪上大量蔥薑絲，淋豉油並潑滾燙熱油激發香氣。'],
    stepsEn: ['Place seabass over scallions on a steam plate.', 'Steam over high boil for 7 mins.', 'Drain plate liquid, top with fresh scallions, drizzle soy sauce and smoking oil.'],
    chefTipsZh: '蒸出的水分帶有魚腥味，出鍋第一時間倒掉是魚肉鮮甜的秘訣。',
    chefTipsEn: 'Always discard liquid after steaming to eliminate any fishiness.',
  },
  {
    id: 'l-tomato-pasta',
    slug: 'fresh-tomato-basil-spaghetti',
    zh: '新鮮羅馬番茄羅勒意大利麵',
    en: 'Fresh Roma Tomato Basil Spaghetti',
    meal_type: 'lunch',
    season: 'summer',
    cuisine: 'Italian',
    prep_time: '20 mins',
    calories: '380 kcal',
    image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['vegetarian', 'dairy_free', 'seasonal_produce'],
    ingredientsZh: [{ name: '全麥意大利細麵', amount: '85g' }, { name: '熟透羅馬番茄', amount: '2個 (200g)' }, { name: '新鮮羅勒葉', amount: '10片' }, { name: '大蒜與初榨橄欖油', amount: '15ml' }],
    ingredientsEn: [{ name: 'Spaghetti', amount: '85g' }, { name: 'Roma Tomatoes', amount: '2 pcs (200g)' }, { name: 'Fresh Basil', amount: '10 leaves' }, { name: 'Garlic & Olive Oil', amount: '15ml' }],
    stepsZh: ['意麵入沸水加鹽煮8分鐘至剛好有嚼勁（Al Dente）。', '平底鍋橄欖油炒香蒜片，下番茄丁慢熬成濃稠番茄醬。', '倒入意麵與新鮮羅勒葉大火翻裹均勻出鍋。'],
    stepsEn: ['Boil pasta in salted water for 8 mins until al dente.', 'Sauté garlic in olive oil, simmer crushed tomatoes into a rich sauce.', 'Toss pasta and fresh basil in sauce to coat completely.'],
    chefTipsZh: '加入兩勺煮麵水乳化番茄醬，能讓醬汁緊緊附著在麵條上。',
    chefTipsEn: 'Add starchy pasta water to emulsify the sauce smoothly around pasta.',
  },
  {
    id: 'l-beef-pho',
    slug: 'vietnamese-beef-pho',
    zh: '越式鮮安格斯牛肉清湯河粉',
    en: 'Vietnamese Angus Beef Pho',
    meal_type: 'lunch',
    season: 'spring',
    cuisine: 'Vietnamese',
    prep_time: '20 mins',
    calories: '410 kcal',
    image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['dairy_free', 'gluten_free', 'high_protein'],
    ingredientsZh: [{ name: '薄切安格斯牛柳片', amount: '130g' }, { name: '純米河粉', amount: '120g' }, { name: '牛骨香草清高湯', amount: '400ml' }, { name: '九層塔、豆芽與青檸', amount: '適量' }],
    ingredientsEn: [{ name: 'Thin Beef Tenderloin Slices', amount: '130g' }, { name: 'Rice Pho Noodles', amount: '120g' }, { name: 'Beef Bone Broth', amount: '400ml' }, { name: 'Basil, Bean Sprouts, Lime', amount: 'to taste' }],
    stepsZh: ['河粉焯水30秒撈出置於大碗。', '生牛肉薄片均勻鋪在河粉頂部。', '將滾沸的牛骨高湯直接澆在牛肉上燙至粉嫩，配九層塔與青檸汁。'],
    stepsEn: ['Blanch noodles for 30s and place in bowl.', 'Arrange raw beef slices neatly across noodles.', 'Pour boiling beef broth directly over beef to gently cook; serve with herbs and lime.'],
    chefTipsZh: '高湯必須達到滾沸狀態再澆入，方能瞬間鎖住鮮牛肉的嫩度。',
    chefTipsEn: 'Broth must be at a rolling boil to flash-cook beef slices instantly.',
  },
  {
    id: 'l-truffle-risotto',
    slug: 'porcini-truffle-risotto',
    zh: '野生牛肝菌黑松露意大利燉飯',
    en: 'Porcini Truffle Italian Risotto',
    meal_type: 'lunch',
    season: 'winter',
    cuisine: 'Italian',
    prep_time: '30 mins',
    calories: '460 kcal',
    image_url: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['vegetarian', 'gluten_free'],
    ingredientsZh: [{ name: '意大利Arborio米', amount: '100g' }, { name: '乾燥牛肝菌', amount: '25g' }, { name: '帕瑪森乾酪', amount: '20g' }, { name: '黑松露醬', amount: '1茶匙' }],
    ingredientsEn: [{ name: 'Arborio Rice', amount: '100g' }, { name: 'Dried Porcini', amount: '25g' }, { name: 'Parmesan Cheese', amount: '20g' }, { name: 'Truffle Paste', amount: '1 tsp' }],
    stepsZh: ['牛肝菌溫水泡發，濾出菌菇清湯備用。', '洋蔥碎炒香米粒，分次加入菌菇湯攪拌至米芯微軟。', '關火拌入帕瑪森芝士與松露醬收汁。'],
    stepsEn: ['Steep porcini in warm water, reserve broth.', 'Sauté onion and rice, add broth gradually while stirring.', 'Fold in parmesan and truffle paste off the heat.'],
    chefTipsZh: '分次加入熱高湯並不間斷攪拌，能充分釋放米粒澱粉形成奶油般濃稠感。',
    chefTipsEn: 'Gradually adding hot broth and stirring releases starch for creaminess.',
  },
  {
    id: 'l-chicken-quinoa-bowl',
    slug: 'grilled-chicken-quinoa-bowl',
    zh: '彩椒藜麥嫩烤香草雞胸暖碗',
    en: 'Grilled Herb Chicken Quinoa Warm Bowl',
    meal_type: 'lunch',
    season: 'summer',
    cuisine: 'Mediterranean',
    prep_time: '22 mins',
    calories: '420 kcal',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['high_protein', 'gluten_free', 'low_fat', 'seasonal_produce'],
    ingredientsZh: [{ name: '低脂雞胸肉', amount: '160g' }, { name: '三色藜麥飯', amount: '90g' }, { name: '彩色小番茄與黃瓜', amount: '80g' }, { name: '第戎檸檬橄欖油汁', amount: '15ml' }],
    ingredientsEn: [{ name: 'Chicken Breast', amount: '160g' }, { name: 'Tri-color Quinoa', amount: '90g' }, { name: 'Tomatoes & Cucumber', amount: '80g' }, { name: 'Lemon Dijon Dressing', amount: '15ml' }],
    stepsZh: ['雞胸肉用黑胡椒海鹽醃製，平底鍋雙面各煎4分鐘至熟切片。', '碗底盛入溫熱藜麥飯，碼入切塊時蔬。', '擺上香煎雞胸肉片，淋上檸檬油醋汁。'],
    stepsEn: ['Sear seasoned chicken 4 mins per side, rest and slice.', 'Assemble warm quinoa and diced vegetables in bowl.', 'Top with chicken slices and drizzle lemon dressing.'],
    chefTipsZh: '雞胸肉出鍋後靜置2分鐘再切，肉汁不會流失。',
    chefTipsEn: 'Rest chicken for 2 mins before carving to retain all moisture.',
  },
  {
    id: 'l-salmon-ochazuke',
    slug: 'japanese-salmon-ochazuke',
    zh: '日式香煎三文魚柴魚茶泡飯',
    en: 'Japanese Seared Salmon Ochazuke',
    meal_type: 'lunch',
    season: 'autumn',
    cuisine: 'Japanese',
    prep_time: '15 mins',
    calories: '390 kcal',
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['high_protein', 'dairy_free', 'seasonal_produce'],
    ingredientsZh: [{ name: '三文魚排', amount: '140g' }, { name: '越光米飯', amount: '120g' }, { name: '柴魚煎茶高湯', amount: '250ml' }, { name: '海苔絲、白芝麻與山葵', amount: '少許' }],
    ingredientsEn: [{ name: 'Salmon Fillet', amount: '140g' }, { name: 'Steamed Rice', amount: '120g' }, { name: 'Dashi Green Tea Broth', amount: '250ml' }, { name: 'Nori, Sesame & Wasabi', amount: 'pinch' }],
    stepsZh: ['三文魚皮朝下煎至酥脆金黃，壓碎成大塊。', '米飯盛入碗中，鋪上香煎三文魚塊與海苔絲。', '沿碗邊緩緩注入滾燙的柴魚綠茶湯即可。'],
    stepsEn: ['Sear salmon until skin is crispy, flake into chunks.', 'Place rice in bowl, top with salmon flakes and nori.', 'Pour hot dashi tea broth around edges to serve.'],
    chefTipsZh: '茶湯從碗邊注入，可保持三文魚皮長久酥脆。',
    chefTipsEn: 'Pour tea broth along the edge to keep the fish skin crisp.',
  },
  {
    id: 'l-vegetable-soup',
    slug: 'rustic-autumn-vegetable-soup',
    zh: '鄉村時令南瓜蔬菜濃湯佐麵包',
    en: 'Rustic Autumn Vegetable Soup',
    meal_type: 'lunch',
    season: 'autumn',
    cuisine: 'French',
    prep_time: '25 mins',
    calories: '290 kcal',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['vegetarian', 'gluten_free', 'seasonal_produce'],
    ingredientsZh: [{ name: '時令南瓜與胡蘿蔔', amount: '200g' }, { name: '洋蔥與西芹', amount: '60g' }, { name: '自熬蔬菜清高湯', amount: '300ml' }],
    ingredientsEn: [{ name: 'Pumpkin & Carrots', amount: '200g' }, { name: 'Onion & Celery', amount: '60g' }, { name: 'Vegetable Broth', amount: '300ml' }],
    stepsZh: ['蔬菜丁入鍋用橄欖油炒香軟化。', '倒入蔬菜高湯煮沸，轉中小火慢燉15分鐘。', '用攪拌棒打成絲滑濃湯，撒少許黑胡椒。'],
    stepsEn: ['Sauté diced vegetables in olive oil until soft.', 'Add broth and simmer gently for 15 mins.', 'Blend until velvety smooth and season with pepper.'],
    chefTipsZh: '出鍋前淋半茶匙初榨橄欖油，能讓濃湯口感更加油潤香濃。',
    chefTipsEn: 'A swirl of extra virgin olive oil before serving adds luxurious sheen.',
  },

  // ================= 晚餐 (10道独立菜品与独家图片) =================
  {
    id: 'd-lamb-chops',
    slug: 'herb-crusted-roasted-lamb-chops',
    zh: '香草第戎芥末烤嫩羊小排',
    en: 'Herb-Crusted Roasted Lamb Chops',
    meal_type: 'dinner',
    season: 'autumn',
    cuisine: 'Western',
    prep_time: '30 mins',
    calories: '510 kcal',
    image_url: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['high_protein', 'gluten_free', 'keto_friendly', 'seasonal_produce'],
    ingredientsZh: [{ name: '法式修整羊小排', amount: '3支 (240g)' }, { name: '新鮮迷迭香與百里香', amount: '2枝' }, { name: '第戎芥末醬', amount: '15g' }, { name: '大蒜與橄欖油', amount: '15ml' }],
    ingredientsEn: [{ name: 'Frenched Lamb Chops', amount: '3 pcs (240g)' }, { name: 'Fresh Rosemary & Thyme', amount: '2 sprigs' }, { name: 'Dijon Mustard', amount: '15g' }, { name: 'Garlic & Olive Oil', amount: '15ml' }],
    stepsZh: ['羊排抹勻第戎芥末、香草碎與粗海鹽。', '熱鍋每面大火煎1分鐘鎖住肉汁。', '移入200°C烤箱烤製8分鐘至五分熟（Medium），靜置3分鐘切分。'],
    stepsEn: ['Rub lamb chops with mustard, herbs, and sea salt.', 'Sear 1 min per side in hot pan to seal in juices.', 'Roast at 200°C for 8 mins for medium doneness; rest 3 mins.'],
    chefTipsZh: '塗抹第戎芥末能有效中和羊羶並烤出酥脆焦香外殼。',
    chefTipsEn: 'Dijon mustard mellows gaminess and helps form a savory crust.',
  },
  {
    id: 'd-angus-steak',
    slug: 'pan-seared-angus-ribeye-asparagus',
    zh: '香煎安格斯肉眼牛排佐嫩蘆筍',
    en: 'Pan-Seared Angus Ribeye with Asparagus',
    meal_type: 'dinner',
    season: 'summer',
    cuisine: 'Western',
    prep_time: '25 mins',
    calories: '520 kcal',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['keto_friendly', 'high_protein', 'gluten_free', 'seasonal_produce'],
    ingredientsZh: [{ name: '安格斯肉眼牛排', amount: '220g' }, { name: '鮮嫩蘆筍', amount: '6根 (100g)' }, { name: '發酵黃油與蒜瓣', amount: '15g' }, { name: '迷迭香', amount: '1枝' }],
    ingredientsEn: [{ name: 'Angus Ribeye Steak', amount: '220g' }, { name: 'Fresh Asparagus', amount: '6 spears (100g)' }, { name: 'Butter & Garlic', amount: '15g' }, { name: 'Rosemary', amount: '1 sprig' }],
    stepsZh: ['牛排提前回溫，吸乾水分撒粗海鹽黑胡椒。', '鐵鍋大火燒冒煙，牛排每面煎90秒上色。', '加入黃油蒜瓣迷迭香淋油煎1分鐘，出鍋靜置5分鐘。'],
    stepsEn: ['Bring steak to room temp, pat dry and season.', 'Sear in smoking skillet for 90s per side.', 'Baste with melted butter, garlic, and herbs; rest 5 mins.'],
    chefTipsZh: '牛排下鍋前必須回歸室溫，煎好後靜置5分鐘鎖住肉汁。',
    chefTipsEn: 'Rest steak for 5 mins after cooking so juices redistribute evenly.',
  },
  {
    id: 'd-roast-chicken',
    slug: 'french-rosemary-roast-chicken',
    zh: '法式迷迭香香脆烤春雞佐蘆筍',
    en: 'French Rosemary Roast Spring Chicken',
    meal_type: 'dinner',
    season: 'spring',
    cuisine: 'French',
    prep_time: '35 mins',
    calories: '480 kcal',
    image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['gluten_free', 'high_protein', 'seasonal_produce'],
    ingredientsZh: [{ name: '嫩春雞半隻', amount: '450g' }, { name: '新鮮迷迭香與檸檬片', amount: '適量' }, { name: '嫩蘆筍', amount: '8根' }, { name: '海鹽黑胡椒橄欖油', amount: '適量' }],
    ingredientsEn: [{ name: 'Spring Baby Chicken', amount: '1/2 (450g)' }, { name: 'Rosemary & Lemon', amount: 'to taste' }, { name: 'Asparagus', amount: '8 spears' }, { name: 'Olive Oil & Seasoning', amount: 'to taste' }],
    stepsZh: ['春雞抹勻香草海鹽橄欖油。', '烤箱預熱200°C，雞皮朝上烤25分鐘至金黃酥脆。', '最後5分鐘放入蘆筍同烤出爐。'],
    stepsEn: ['Rub chicken with herbs, salt, and olive oil.', 'Roast in 200°C oven for 25 mins until skin is crispy.', 'Toss in asparagus for the final 5 mins.'],
    chefTipsZh: '雞皮表面徹底擦乾再抹油烤，能烤出玻璃般薄脆的雞皮。',
    chefTipsEn: 'Ensure skin is completely dry before baking for an ultra-crispy crust.',
  },
  {
    id: 'd-seafood-paella',
    slug: 'spanish-saffron-seafood-paella',
    zh: '西班牙藏紅花海鮮燉飯',
    en: 'Spanish Saffron Seafood Paella',
    meal_type: 'dinner',
    season: 'spring',
    cuisine: 'Spanish',
    prep_time: '35 mins',
    calories: '470 kcal',
    image_url: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['gluten_free', 'high_protein', 'seasonal_produce'],
    ingredientsZh: [{ name: '西班牙短粒米', amount: '130g' }, { name: '海捕大蝦與青口貝', amount: '各4只 (200g)' }, { name: '藏紅花高湯', amount: '350ml' }, { name: '紅甜椒丁', amount: '50g' }],
    ingredientsEn: [{ name: 'Spanish Rice', amount: '130g' }, { name: 'Prawns & Mussels', amount: '4 pcs each (200g)' }, { name: 'Saffron Broth', amount: '350ml' }, { name: 'Bell Pepper', amount: '50g' }],
    stepsZh: ['熱鍋炒香彩椒與蒜末，倒入米粒翻炒1分鐘。', '注入金黃藏紅花高湯慢煮15分鐘。', '鋪上海鮮加蓋燜煮5分鐘形成底部脆米鍋巴。'],
    stepsEn: ['Sauté peppers and garlic, toast rice for 1 min.', 'Simmer with golden saffron broth for 15 mins.', 'Arrange seafood and cook 5 mins to develop crispy socarrat.'],
    chefTipsZh: '下高湯後切忌翻動米飯，才能結出地道香脆的鍋巴。',
    chefTipsEn: 'Do not stir once simmering begins to allow the crispy bottom crust to form.',
  },
  {
    id: 'd-miso-cod',
    slug: 'kyoto-saikyo-miso-baked-cod',
    zh: '京都白味噌焗深海銀鱈魚柳',
    en: 'Kyoto Saikyo Miso Baked Black Cod',
    meal_type: 'dinner',
    season: 'winter',
    cuisine: 'Japanese',
    prep_time: '20 mins',
    calories: '360 kcal',
    image_url: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['gluten_free', 'high_protein', 'dairy_free', 'seasonal_produce'],
    ingredientsZh: [{ name: '深海銀鱈魚柳', amount: '180g' }, { name: '京都白味噌', amount: '30g' }, { name: '味醂與清酒', amount: '15ml' }],
    ingredientsEn: [{ name: 'Black Cod Fillet', amount: '180g' }, { name: 'Saikyo White Miso', amount: '30g' }, { name: 'Mirin & Sake', amount: '15ml' }],
    stepsZh: ['銀鱈魚柳均勻塗抹白味噌醃料醃製。', '烤箱200°C烤10分鐘至表面焦糖化微焦。', '出爐搭配青檸片溫熱享用。'],
    stepsEn: ['Coat cod evenly in miso marinade.', 'Bake at 200°C for 10 mins until caramelized and tender.', 'Serve with a slice of fresh lime.'],
    chefTipsZh: '烤前用紙巾輕輕拭去多餘表面味噌，防止高溫烤焦。',
    chefTipsEn: 'Wipe excess miso off before baking to prevent charring.',
  },
  {
    id: 'd-green-curry',
    slug: 'thai-aromatic-green-curry-chicken',
    zh: '泰式椰香青咖哩嫩雞佐時蔬',
    en: 'Thai Aromatic Green Curry Chicken',
    meal_type: 'dinner',
    season: 'summer',
    cuisine: 'Thai',
    prep_time: '25 mins',
    calories: '450 kcal',
    image_url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['gluten_free', 'dairy_free', 'seasonal_produce'],
    ingredientsZh: [{ name: '去骨雞腿肉', amount: '200g' }, { name: '泰式綠咖哩醬', amount: '30g' }, { name: '純椰漿', amount: '160ml' }, { name: '泰國圓茄與九層塔', amount: '80g' }],
    ingredientsEn: [{ name: 'Chicken Thigh', amount: '200g' }, { name: 'Green Curry Paste', amount: '30g' }, { name: 'Coconut Milk', amount: '160ml' }, { name: 'Thai Eggplants & Basil', amount: '80g' }],
    stepsZh: ['椰漿小火炒出椰油，溶入綠咖哩醬炒香雞肉塊。', '加入圓茄與高湯慢燉8分鐘。', '出鍋前撕入九層塔葉提香。'],
    stepsEn: ['Simmer coconut milk to release oil, sauté curry paste and chicken.', 'Add eggplants and simmer for 8 mins.', 'Toss fresh basil leaves right before serving.'],
    chefTipsZh: '九層塔在關火前最後加入，能保留清香不發黑。',
    chefTipsEn: 'Add fresh basil at the very last moment to retain fragrance and color.',
  },
  {
    id: 'd-salmon-greens',
    slug: 'pan-seared-salmon-seasonal-greens',
    zh: '香煎三文魚柳佐黑松露時蔬',
    en: 'Pan-Seared Salmon with Truffle Greens',
    meal_type: 'dinner',
    season: 'summer',
    cuisine: 'Western',
    prep_time: '25 mins',
    calories: '490 kcal',
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop&q=80',
    dietary_tags: ['high_protein', 'gluten_free', 'seasonal_produce'],
    ingredientsZh: [{ name: '挪威三文魚柳', amount: '200g' }, { name: '蘆筍與小番茄', amount: '100g' }, { name: '黑松露醬', amount: '1茶匙' }, { name: '海鹽黑胡椒', amount: '少許' }],
    ingredientsEn: [{ name: 'Salmon Fillet', amount: '200g' }, { name: 'Asparagus & Tomatoes', amount: '100g' }, { name: 'Truffle Paste', amount: '1 tsp' }, { name: 'Sea Salt & Pepper', amount: 'pinch' }],
    stepsZh: ['三文魚皮朝下慢煎4分鐘至金黃酥脆，翻面煎熟。', '原鍋翻炒時蔬並拌入黑松露醬。', '裝盤時蔬鋪底，放上香煎三文魚柳。'],
    stepsEn: ['Sear salmon skin-side down for 4 mins until crispy, flip.', 'Sauté vegetables in same pan with truffle paste.', 'Plate greens and place crispy salmon on top.'],
    chefTipsZh: '魚皮下鍋前徹底吸乾水分，能煎出無比酥脆的口感。',
    chefTipsEn: 'Pat skin bone-dry before cooking to guarantee a crunchy texture.',
  },
];

// Fisher-Yates 严格洗牌生成器（确保每次点击 100% 随机刷新且早中晚 21 格绝不重复）
export function generateShuffledWeeklyPlan(
  season: ThemeMode,
  lang: Lang,
  _restrictions: Set<any>
): Dish[][] {
  const isZh = lang !== 'en';

  const breakfasts = VERIFIED_MASTER_POOL.filter((d) => d.meal_type === 'breakfast');
  const lunches = VERIFIED_MASTER_POOL.filter((d) => d.meal_type === 'lunch');
  const dinners = VERIFIED_MASTER_POOL.filter((d) => d.meal_type === 'dinner');

  function shuffle<T>(array: T[]): T[] {
    const arr = [...array];
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }

  const sB = shuffle(breakfasts);
  const sL = shuffle(lunches);
  const sD = shuffle(dinners);

  const plan: Dish[][] = [];

  for (let day = 0; day < 7; day++) {
    const bRaw = sB[day % sB.length];
    const lRaw = sL[day % sL.length];
    const dRaw = sD[day % sD.length];

    const toDish = (raw: VerifiedDishData): Dish => ({
      id: `${raw.id}-${Date.now()}-${Math.random()}`,
      slug: `${raw.slug}-${Date.now()}`,
      title: { en: raw.en, zhCN: raw.zh, zhTW: raw.zh, zh: raw.zh },
      title_zh: raw.zh,
      title_en: raw.en,
      season: season,
      meal_type: raw.meal_type,
      cuisine: raw.cuisine,
      prep_time: raw.prep_time,
      calories: raw.calories,
      image_url: raw.image_url,
      dietary_tags: raw.dietary_tags,
      ingredients: isZh ? raw.ingredientsZh : raw.ingredientsEn,
      instructions: (isZh ? raw.stepsZh : raw.stepsEn).map((t, idx) => ({ step: idx + 1, text: t })),
      chef_tips: isZh ? raw.chefTipsZh : raw.chefTipsEn,
    });

    plan.push([toDish(bRaw), toDish(lRaw), toDish(dRaw)]);
  }

  return plan;
}